### ISSUE TITLE
Ansible Galaxy

### ISSUE THREAD

**Issue by noplanman** [angristan/ansible-roles#2]
I noticed you don't upload your roles to Ansible Galaxy. Why not?

What is the best way to make use of your roles? Clone locally?

**Comment by angristan** [comment]
I don't really remember why I stopped publishing them on Galaxy. Until then you can use them from Github: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-a-collection-from-a-git-repository

**Comment by noplanman** [comment]
Ok, thanks for the link with the explanation 🙏
